### ISSUE TITLE
Не генерируется интерфейс

### ISSUE THREAD

**Issue by IU-dev** [dvelum/dvelum#41]
FastCGI, PHP 7.2
Не генерируется интерфейс при генерации через "Модули".
В дизайнере интерфейсов тоже "пустой" интерфейс.
![image](https://user-images.githubusercontent.com/33807454/48301643-8f374d80-e50a-11e8-93cc-149b20a28c25.png)
![image](https://user-images.githubusercontent.com/33807454/48301647-95c5c500-e50a-11e8-9bd7-cfa97664c7c9.png)

**Comment by IU-dev** [comment]
Получилось пофиксить.
В целях сортировки автогенерируемых полей в ORM писал 1_Name, 2_Surname и так далее, из-за чего возникала ошибка ExtJS.

**Comment by k-samuel** [comment]
Добрый день. Не могли бы вы предоставить конфиг файл orm объекта?  Так же не совсем понятно о какой сортировке идет речь и зачем она в именах полей.

**Comment by IU-dev** [comment]
Подскажите пожалуйста, где достать конфиг.
Сортировка нужна вот для чего. Как я понял, генератор интерфейса генерирует поля в форме добавления по алфавиту. Чтобы сделать поля в нужном мне порядке, использовал для шифрования 01_Имя, 02_Имя и т.д.

**Comment by k-samuel** [comment]
Поля можно двигать в дизайнере (дерево проекта drag'n'drop)
Настройки лежат в https://github.com/dvelum/dvelum/tree/dev-2.x/application/configs/common/local/objects.  Имя файла - имя объекта

**Comment by k-samuel** [comment]
Посмотрите https://dvelum.ru/cookbook_screencast_phonebook.html
